### ISSUE TITLE
importing libfwsi for plaso

### ISSUE THREAD

**Issue by archey** [libyal/libfwsi#1]
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 31, in <module>
    from plaso.frontend import frontend
  File "/usr/lib/python2.7/site-packages/plaso/frontend/frontend.py", line 36, in <module>
    from plaso import parsers   # pylint: disable=unused-import
  File "/usr/lib/python2.7/site-packages/plaso/parsers/__init__.py", line 26, in <module>
    from plaso.parsers import custom_destinations
  File "/usr/lib/python2.7/site-packages/plaso/parsers/custom_destinations.py", line 31, in <module>
    from plaso.parsers import winlnk
  File "/usr/lib/python2.7/site-packages/plaso/parsers/winlnk.py", line 27, in <module>
    from plaso.parsers.shared import shell_items
  File "/usr/lib/python2.7/site-packages/plaso/parsers/shared/shell_items.py", line 20, in <module>
    import pyfwsi
ImportError: /usr/lib/python2.7/site-packages/pyfwsi.so: undefined symbol: libfwsi_notify_set_verbose

We have built the deps of libcsytem v20150101 and libbfio v20150102 before building libfwsi. Is this fixed in the git src and if so can you tag it so we can pull the tag?

Thanks

**Comment by joachimmetz** [comment]
> Is  this fixed in the git src and if so can you tag it so we can pull the tag?

I push an updated version,

**Comment by joachimmetz** [comment]
So the issue should only surface with debug and verbose output and was fixed in https://github.com/libyal/libfwsi/commit/b8dca6c56ad74abc853eb3ac8318d170334b1c92
