### ISSUE TITLE
current libfwsi-python on pypi won't install correctly

### ISSUE THREAD

**Issue by puccia** [libyal/libfwsi#11]
The current package seems not to install correctly through pip.

Steps to reproduce:

```
$ virtualenv test
Running virtualenv with interpreter /usr/bin/python2
[...]

Installing setuptools, pkg_resources, pip, wheel...done.
$ . test/bin/activate
(test) $ pip install libfwsi-python
Collecting libfwsi-python
  Using cached libfwsi-python-20180330.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oeAmFM/libfwsi-python/setup.py", line 285, in <module>
        project_information = ProjectInformation()
      File "/tmp/pip-build-oeAmFM/libfwsi-python/setup.py", line 182, in __init__
        self._ReadConfigureAc()
      File "/tmp/pip-build-oeAmFM/libfwsi-python/setup.py", line 207, in _ReadConfigureAc
        file_object = open("configure.ac", "rb")
    IOError: [Errno 2] No such file or directory: 'configure.ac'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oeAmFM/libfwsi-python/
```

**Comment by joachimmetz** [comment]
Issue introduced in https://github.com/libyal/libfwsi/commit/5429e342ed153bdea08be98c76e192401c26d30d, this is related to how setup.py creates source distributions.

**Comment by joachimmetz** [comment]
Issue fixed in https://github.com/libyal/libfwsi/commit/86385ecb17c4de777b01bd8cff7b6cb5c24a7842.
