### ISSUE TITLE
Import Error: Undefined Symbol after compiling from source

### ISSUE THREAD

**Issue by bf** [libyal/libfwsi#3]
I experience an error when starting log2timeline.py after compiling libfwsi from git into pyfwsi on an arch linux system.

```
> log2timeline.py --version
Traceback (most recent call last):
  File "/usr/bin/log2timeline.py", line 5, in <module>
    pkg_resources.run_script('plaso==1.2.1-20150206', 'log2timeline.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 528, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1401, in run_script
  File "/usr/lib/python2.7/site-packages/plaso-1.2.1_20150206-py2.7.egg/EGG-INFO/scripts/log2timeline.py", line 31, in <module>
    
  File "build/bdist.linux-x86_64/egg/plaso/frontend/frontend.py", line 36, in <module>
  File "build/bdist.linux-x86_64/egg/plaso/parsers/__init__.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/plaso/parsers/custom_destinations.py", line 31, in <module>
  File "build/bdist.linux-x86_64/egg/plaso/parsers/winlnk.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/plaso/parsers/shared/shell_items.py", line 20, in <module>
ImportError: /usr/lib/python2.7/site-packages/pyfwsi.so: undefined symbol: libfwsi_file_entry_extension_get_access_time
```

The package was compiled via:

```
env PYTHON=python2.7 PYTHON_VERSION=2.7 ./configure --enable-python;
make;
sudo make install;
cd pyfwsi;
python2.7 setup.py build; 
sudo python2.7 setup.py install;
```

The file `/usr/lib/python2.7/site-packages/pyfwsi.so` has been created through the compiling steps.

Sorry if this may be a stupid question, but I compiled `libsigscan` just before that, and experienced no problems with the same command.

**Comment by bf** [comment]
Okay, funny how problems solve themselves once you formulate them in writing for others. After spending 2 hours trying to compile the library, I changed to compile command to `env PYTHON=python2.7 ./configure --enable-python --prefix=/usr; and make ; and sudo make install`and it worked.

Thanks again for the nice software you created, and sorry for spamming your issue tracker :-)

**Comment by joachimmetz** [comment]
> Okay, funny how problems solve themselves once you formulate them in writing for others. 

Nope sounds familiar ;) It helps because you need to make what you are doing more verbose and hence think about the problem from a different perspective.

Good to hear you have solved it. Sounds to me you might have 2 copies of libfwsi on your installation check /usr/local/lib and /usr/lib (or equiv).
